language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: PSmMw3c0NBC/7iBi3FtdnwASj6LDB6Xb/QkWqq8LEHpDcdpYzcT0d8DIjdZsVGwZNZxOVbxSUY2aHWbrqNwj9biw6qmbCQ6PqihdeCq8K2C6Ep3GNQLNztFc+V329j5ufm7+3Ijcf4vNJFC5kWtXeFn+Bn8oSjFDL4zV+yAr0mNrq2XosD3ZfVpYkegXcbwoAaOsJvUuh2vdl82qLhNYw1OQT+nofBvpIITM+VCeaADSImrc/io2R7qPARvW4OCuIXgQ4eSvISKr3jvPZp0X1w3inZ3391kQf5dE0taNBIxJ7c700FAX8+vZ04AkWTMJjPI/how6tUCscswmVMZtOvYpHs7EZf1rE0Pna73VoVvVZM4Bh5CSZvtBXRXItiRcJXY4EU2+OqUOG/F/F3Zgq1+gXF9hTv/E+hYze1qBsZtwgG49s2RZxVwj0/VDKbKUzTrEOG4oG57D1jGgirNs3QEzjSsOIRznzCZF3qrbTIcAo5GsQpyIZQPEvWI/fW0Y3ToD8KU7J6+UjZIAn660FCghf5ZDgR94OgXQ7xS/Uqf2e8hpCTOX7FFKrjNra0cElmiqHsbHstnEFtZx4xC8V0GgWRgkfM504/g5idyWq2rJ2YVnBkWVCAVvRHzjcJH74N55yjtSUBFkzNANeiR62tQK2rucnF3D9m89lygPs44=
